dna=rep(c("A","T","G","C"),c(12,8,11,9))
fdna=factor(dna)
summary(1:10)[2]
summary(dna)
summary(fdna)[c("A","T")]
ratio=(summary(fdna)/length(dna))*100
ratio
sample(dna,size=8,replace=FALSE)
sample(dna,size=88,replace=FALSE)
sample(dna,size=88,replace=TRUE)
dna2=rep(c("A","T","G","C"))

dna2=sample(dna,size=10000,replace=T)
fdna2=factor(dna2)
summary(dna2)
summary(fdna2)
ratio2=(summary(fdna2)/length(dna2))*100
ratio2
ratio2/ratio
